<?php
define('TOUR_NAME', 'encyclopedia'); //тип материала
/*
 * 
 * Модуль для вывода материалов типа энцыклопедия
 * 
 */

/**
 * Реализация hook_menu
 * @return type
 */
function custom_encyclopedia_menu() {
    return array(
        'encyclopedia/%' => array(
            'title' => 'Encyclopedia',
            'title callback' => 'encyclopedia_page_title',
            'title arguments' => array(1),
            'type' => MENU_NORMAL_ITEM,
            'page arguments' => array(1),
            'page callback' => 'custom_encyclopedia_page',
            'access arguments' => array('access content'),
        ),
        'encyclopedia' => array(
            'title' => 'Encyclopedia',
            'type' => MENU_NORMAL_ITEM,
            'page callback' => 'custom_encyclopedia_page',
            'access arguments' => array('access content'),
        ),
    );
}

function encyclopedia_page_title($char) {
  return t('Encyclopedia') . ' (' . mb_strtoupper(encodestring_cur($char)) . ')';
}

function custom_encyclopedia_theme() {
    return array(
        'custom_encyclopedia' => array(
            'template' => 'templates/encyclopedy',
            'variables' => array('output' => NULL, 'display' => 'all'),
        ),
        'custom_encyclopedia_item' => array(
            'template' => 'templates/encyclopedy_item',
            'arguments' => array('letter' => NULL, 'content' => NULL, 'count_ress' => NULL),
        )
    );
}

function custom_encyclopedia_page($char = FALSE) {
    $path = drupal_get_path('module', 'custom_encyclopedia');
    drupal_add_css($path . '/custom_encyclopedia.css');
    $count = 0;
    $content = '';
    $output = '';
    $count_ress = 0;
    if (empty ($char)){
        $abc = array('а','б','в','г','д','е','ж','з','и','й','к','л','м','н','о','п','р','с','т','у','ф','х','ц','ч','щ','ш','ь','ы','ъ','э','ю','я'
          ,'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');
        $display = 'all';
        foreach ($abc as $key => $value) {
            $content = '';
            $letter = '';
            $ress = _get_from_base($value);
            if (!empty($ress)){
                $letter = '<a href="/encyclopedia/' . encodestring($value) . '">' . $value . '</a>';
                if (count($ress) > 5){
                    for ($i=0; $i<5; $i++) {
                      $content .= l($ress[$i]->title, 'node/' . $ress[$i]->nid);
                    }
                    $content .= '<a class="see_more" href="/encyclopedia/' . $value . '">Смотреть все</a>';
                }else{
                    foreach ($ress as $key_ress => $value_ress) {
                      $content .= l($value_ress->title, 'node/' . $value_ress->nid);
                    }
                }
                $count++;
                $count_ress = $count % 3;            
                $output .= theme('custom_encyclopedia_item', array('letter' => $letter, 'content' => $content, 'count_ress' => $count_ress));
            }
        }
    }else{      
      if(preg_match("/[a-z,A-Z]/",$char)) {
        $char = encodestring_cur($char);
      }else{
        $char = encodestring($char);
        drupal_goto('encyclopedia/'.$char, array(), '301');

      }


        $ress = _get_from_base($char);
        $display = 'one';
        if (!empty($ress)){
            $letter = $char;
            $modulo = count($ress) % 5;
            if ($modulo == 0){
                $colom_count =  (int)count($ress) / 5;
            }else{
                $colom_count =  (int)(count($ress) / 5)+1;
            }
            $k=0;
            $metacount = 0;
            $outmeta = '<meta name="description" content="Энциклопедия:';
            for ($i=0;$i<=$colom_count;$i++){
                $content .= '<div class="colom_count '.count($ress).'" >';
                for ($j=$k;$j<($k+5);$j++){
                  if(!empty($ress[$j]->title)){
                    $content .= l($ress[$j]->title, 'node/' . $ress[$j]->nid);
                    if($metacount < 7){
                      $outmeta .= ' ' . $ress[$j]->title . ';';
                      $metacount++;
                    }
                  }
                }
                $k += 5;
                $content .= '</div>';
                if ($i == 3 || $i == 7 ){
                  $content .= '<div class="clear" style="border-bottom: 1px solid rgb(130, 137, 144); margin-bottom: 20px; padding-top: 20px;" > </div>';
                }
            }       
            $output .= theme('custom_encyclopedia_item', array('letter' => $letter, 'content' => $content, 'count_ress' => $count_ress));
            $outmeta .= '">';
            drupal_set_html_head($outmeta);
        }else{
          drupal_goto('encyclopedia', array(), '301');
        }
        
    }
    
    return theme('custom_encyclopedia', array('output' => $output, 'display' => $display));
}

function _get_from_base($letter) {    
  $items = db_select('node', 'n')
  ->fields('n', array('nid', 'title'))  
  ->condition('n.status', 1)->condition('n.title', db_like($letter)."%", 'LIKE')->condition('n.type', 'encyclopedia')
  ->execute()->fetchAll();
  return (array)$items;
}

// функция превода текста с кириллицы в транслит
function encodestring($st){
  $st=strtr($st,
      array(
          'а'=>'a','б'=>'b','в'=>'v','г'=>'g','д'=>'d','е'=>'e',"ж"=>"zh",'з'=>'z','и'=>'i','й'=>'y','к'=>'k','л'=>'l',
          'м'=>'m','н'=>'n','о'=>'o','п'=>'p','р'=>'r','с'=>'s','т'=>'t','у'=>'u','ф'=>'f','х'=>'h',"ц"=>"ts","ч"=>"ch",
          "ш"=>"sh","щ"=>"shch", "ю"=>"yu", "я"=>"ya", "э"=>"ie"
      )
  );
  return $st;
}

// функция превода текста с транслита в кириллицу
function encodestring_cur($st){
  $st=strtr($st,
      array_flip(array(
              'а'=>'a','б'=>'b','в'=>'v','г'=>'g','д'=>'d','е'=>'e',"ж"=>"zh",'з'=>'z','и'=>'i','й'=>'y','к'=>'k','л'=>'l',
              'м'=>'m','н'=>'n','о'=>'o','п'=>'p','р'=>'r','с'=>'s','т'=>'t','у'=>'u','ф'=>'f','х'=>'h',"ц"=>"ts","ч"=>"ch",
              "ш"=>"sh","щ"=>"shch", "ю"=>"yu", "я"=>"ya", "э"=>"ie"
          )
      )
  );
  return $st;
}